"""create followup_answers

Revision ID: f1e14bf37bc6
Revises: 
Create Date: 2025-10-02 10:38:39.975404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e14bf37bc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consult_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hashed', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_medical_history', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('consult_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=255), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['consult_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consult_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['consult_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('primary_question_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['consult_forms.id'], ),
    sa.ForeignKeyConstraint(['primary_question_id'], ['consult_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followup_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=255), nullable=False),
    sa.Column('parent_question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_question_id'], ['consult_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followup_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['followup_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followup_answers')
    op.drop_table('followup_questions')
    op.drop_table('consultations')
    op.drop_table('consult_answers')
    op.drop_table('consult_questions')
    op.drop_table('users')
    op.drop_table('consult_forms')
    # ### end Alembic commands ###
